Update 2013_12_12_093641_add_remaining_columns_in_users_table.php
Caused by
PDOException: SQLSTATE[HY000]: General error: 1364 Field 'twitter_url' doesn't have a default value

Caused by
PDOException: SQLSTATE[HY000]: General error: 1364 Field 'facebook_url' doesn't have a default value

Caused by
PDOException: SQLSTATE[HY000]: General error: 1364 Field 'github_url' doesn't have a default value

Caused by
PDOException: SQLSTATE[HY000]: General error: 1364 Field 'website_url' doesn't have a default value

Caused by
PDOException: SQLSTATE[HY000]: General error: 1364 Field 'photo_url' doesn't have a default value

Caused by
PDOException: SQLSTATE[HY000]: General error: 1364 Field 'about_me' doesn't have a default value