Update 2013_12_11_013559_add_description_credits_to_resource_deleted_at_in_snippets_table.php
Caused by
PDOException: SQLSTATE[HY000]: General error: 1364 Field 'description' doesn't have a default value

Caused by
PDOException: SQLSTATE[HY000]: General error: 1364 Field 'credits_to' doesn't have a default value

Caused by
PDOException: SQLSTATE[HY000]: General error: 1364 Field 'resource' doesn't have a default value